-- Carga inicial de ejercicios desde PDF
insert into public.exercises (code, title, description, video_url)
values
  ('001-NERVE-SLIDE-FLOSS-SCIATIC', 'Nerve slide floss Sciatic', 'Lleva la cabeza hacia atrás mientras extiendes la rodilla Después lleva la cabeza hacia delante y flex rodilla', NULL),
  ('002-MASAJE-MIOFASCIAL-DE-PLANTA-', 'Masaje miofascial de planta del pie con pelota', 'Masajea lentamente Puedes pararte y presionar sobre los puntos de mayor tensión', NULL),
  ('003-TOE-FINGER-ELEPHANT-WALK', 'Toe finger elephant walk', 'Moviliza de manera dinámica los dos pies, uno se apoya y el otro de puntillas, estirando el dedo “gordo de los pies. A diferencia del video puedes apoyar los brazos en un banco', NULL),
  ('004-MASAJE-MIOFASCIAL-DE-SOLEO', 'Masaje miofascial de soleo', 'Masajea lentamente Puedes pararte y presionar sobre los puntos de mayor tensión', NULL),
  ('005-ANKLE-INVERSION-EVERSION', 'Ankle Inversión-eversion', NULL, NULL),
  ('006-ANKLE-INVERSION-EVERSION-TOW', 'Ankle inversión-eversion towel or slider', 'Rota el tobillo sobre una toalla o slider', NULL),
  ('007-HEEL-SLIDES-DORSIFLEXION', 'Heel slides dorsiflexion', NULL, NULL),
  ('008-ANKLE-BANDED-ADDUCTION', 'Ankle banded adduction', NULL, NULL),
  ('009-PLANTAR-FLEXION', 'Plantar flexion', 'No superar los 0º(que la punta del pie llegue a pauntar hacia el techo pero no hacia ti)', NULL),
  ('010-SEATED-HEEL-RAISES', 'Seated heel raises', NULL, NULL),
  ('011-STANDING-SINGLE-LEG-SOLEUS-R', 'Standing single leg soleus raise', 'Apoya las manos sobre una silla o pared; mantén flexionada la rodilla de apoyo y eleva el talón', NULL),
  ('012-POSTERIOR-TIBIALIS-CALF-RAIS', 'Posterior tibialis calf raise', 'Coloca la pelota debajo de tus maleolos Sujetando la pelota eleva y desciende los pies', NULL),
  ('013-PERONE-PERONEOS-GOMA-ELASTIC', 'Perone Peroneos goma elástica', 'Dejar que la resistencia lleve el pie hacia “dentro” para después llevarlo hacia “afuera Evita rotar la pierna, mueve solo el tobillo Soleo Soleus machine Sentado en máquina elevar el tobillo y aguantar la posición durante el tiempo indicado', NULL),
  ('014-1-LEG-SOLEUS-ISOMETRIC-HOLD', '1 leg soleus isometric hold', NULL, NULL),
  ('015-1-LEG-SOLEUS-RAISE', '1 leg soleus raise', 'Mantén la rodilla flexionada mientras elevas y desciendes el tobillo', NULL),
  ('016-GEMELO-1LEG-ISO-CALF-RAISE', 'Gemelo 1leg iso calf raise', 'Alcanza la máxima altura que pueda Trata de ir retirando las manos de la pared', NULL),
  ('017-ECCENTRIC-ACCENTUATED-CALF-R', 'Eccentric accentuated calf raise', 'Elévate apoyando los dos pies y baja solo con uno Si lo necesitas apoya las manos en la pared', NULL),
  ('018-1-LEG-CALF-RAISE-PRESS-MACHI', '1 leg calf raise press machine', NULL, NULL),
  ('019-FOAM-ROLLER-CUADRICEPS', 'Foam roller cuadriceps', 'Masajea lentamente Puedes pararte y presionar sobre los puntos de mayor tensión', NULL),
  ('020-ISOMETRIC-KNEE-EXTENSION', 'Isometric knee extension', 'Empuja en isometrico Ángulo de 90º', NULL),
  ('021-ECC-1LEG-HAMSTRING-CURL-MACH', 'ECC 1leg hamstring curl machine', 'Flexionar con las dos piernas y extender con una Controlar la extensión', NULL),
  ('022-MASAJE-MIOFASCIAL-DE-ABDUCTO', 'Masaje miofascial de abductores', 'Masajea lentamente Puedes pararte y presionar sobre los puntos de mayor tensión', NULL),
  ('023-MASAJE-MIOFASCIAL-DE-ADUCTOR', 'Masaje miofascial de aductores', 'Masajea lentamente Puedes pararte y presionar sobre los puntos de mayor tensión', NULL),
  ('024-RESIETED-BOX-ELEPHANT-WALK', 'Resieted box elephant walk', 'Trata de mantener la cadera en anteversión, extiendes lentamente las rodillas de manera alternativa', NULL),
  ('025-ELEPHANT-WALK', 'Elephant walk', 'Trata de mantener la cadera en anteversión, extiendes lentamente las rodillas de manera alternativa', NULL),
  ('026-LYING-CROSSOVER-REACH', 'Lying crossover reach', 'Eleva los glúteos del suelo; desde ahí extiende rodilla lo que puedas y eleva brazo contrario; en esa posición realiza respiraciones porfundas', NULL),
  ('027-ADD-CUADRUPED-CIRCLE-ADD', 'ADD Cuadruped circle ADD', 'Deslizar lentamente el slider alejándolo del cuerpo', NULL),
  ('028-ROCKBACK', 'Rockback', 'Apoya el dedo gordo de cada pie tratando que este flexionado', NULL),
  ('029-HALF-KNEELING-OPEN-HIP', 'Half kneeling open hip', NULL, NULL),
  ('030-IR-90-90-INTERNAL-ROTATION', 'IR 90/90 internal rotation', NULL, NULL),
  ('031-LATERAL-HIP-BANDED-DISTRACTI', 'Lateral Hip Banded Distraction', NULL, NULL),
  ('032-HIP-HINGE-1-HIP-BANDED', 'Hip Hinge 1 hip Banded', NULL, NULL),
  ('033-0-43', '(0:43)', 'EXT Glute bridge full foot Activar glúteos justo antes de iniciar movimientos Mantener glúteos activos durante todo el movimiento Elevar y bajar el culo APOYANDO TODA LA PLANTA PIE', NULL),
  ('034-PUENTE-GLUTEO-TALON', 'Puente glúteo talón', 'Activar glúteos justo antes de iniciar movimientos Mantener glúteos activos durante todo el movimiento Elevar y bajar el culo mientras apoyamos los talones', NULL),
  ('035-1LEG-PIRATE-GLUTE-BRIDGE', '1leg pirate glute bridge', 'Activar glúteo justo antes de iniciar movimiento Mantener glúteo activo durante todo el movimiento Tratar de extender la rodilla de la pierna estirada max', NULL),
  ('036-DB-GLUTE-GRIDGE', 'DB Glute gridge', 'Activar glúteos justo antes de iniciar movimientos Mantener glúteos activos durante todo el movimiento Apoyar talones, a diferencia de como en el video', NULL),
  ('037-ECC-GLUTE-BRIDGE-SLIDER', 'ECC glute bridge slider', 'Mantener activos glúteos y core Para alcanzar la intensidad del ..% se puede utilizar una pesa sobre la cadera', NULL),
  ('038-1-LEG-ACENTUATED-GLUTE-BRIDG', '1 leg acentuated glute bridge slider', 'Mantener activos glúteos y core Para alcanzar la intensidad del ..% se puede utilizar una pesa sobre la cadera', NULL),
  ('039-PELVIC', 'Pelvic', 'tilt 90 90 hip lift Rodillas y caderas a 90º; una pelota o bloque entre las rodillas 1ro inhala por la nariz; expande las costillas; empuja la pared y aprieta la pelota 2do exhala; realiza retroversión; levanta la cadera del suelo ligeramente', NULL),
  ('040-FLEX-ECC-PSOAS-LOADING', 'FLEX ECC psoas loading', 'No perder la curvatura lumbar activando core Un peso liviano que no suponga sobreesfuerzo', NULL),
  ('041-KB-PSOAS-FLEX', 'KB Psoas flex', 'No perder la curvatura lumbar activando core Un peso liviano que no suponga sobreesfuerzo', NULL),
  ('042-STANDING-BAND-RESISTED-HIP-F', 'Standing band resisted hip flex', 'A core, evitar durante todo el movimiento que se pierda la curvatura lumbar Activar el glúteo de la pierna apoyada', NULL),
  ('043-ABD-ISOMETRIC-SIDE-LYING-HIP', 'ABD Isometric side lying hip abduction', 'Elevar la pierna y mantener la posición', NULL),
  ('044-ABD-FLOOR-CLAMSHELL-BANDED', 'ABD Floor clamshell banded', 'Espalda alineada Activar glúteo durante el movimiento y activar core', NULL),
  ('045-ABD-ABD-MACHINE', 'ABD ABD machine', 'No perder la curvatura lumbar durante el ejercicio', NULL),
  ('046-ADD-HIP-ADDUTOR-MACHINE', 'ADD Hip addutor machine', 'Mantener espalda alineada', NULL),
  ('047-HIP-ADDUCTION-ISO', 'Hip adduction iso', 'Mantener espalda alineada', NULL),
  ('048-SUPINE-HIP-ADDUCTION-ISO', 'Supine Hip adduction iso', 'Apoyar talones a diferencia de como se muestra en el', NULL),
  ('049-ADDUCTOR-SIDE-PLANK', 'Adductor side plank', 'Activa core y manetén la espalda alineada', NULL),
  ('050-KNEELING-COPENHAGEN-PLANK', 'Kneeling copenhagen plank', 'Activa core y manetén la espalda alineada Dinamic kneeling copenhagen plank Activa core y manetén la espalda alineada', NULL),
  ('051-COPENHAGEN-PLANK', 'Copenhagen plank', 'Activa core y manetén la espalda alineada Dinamic copenhagen plank Activa core y manetén la espalda alineada', NULL),
  ('052-PELVIS', 'Pelvis', 'side lying scissor slides Acostado de lado con caderas flexionadas 90º colocar en muslos un foam roller o pelota; deslizar la pierna de arriba sobre el roller', NULL),
  ('053-FOAM-ROLLER-SACRO-ILIACA', 'Foam roller sacro iliaca', 'Percibir la presión sobre los puntos de tensión No deslizar rápidamente', NULL),
  ('054-SACROILIAC-MOBILIZATION', 'Sacroiliac mobilization', 'Con las caderas semiflexionadas y pies apoyados lleva las rodillas a un lado y al otro', NULL),
  ('055-ER-ISO-WALL-SHOULDER-EXTERNA', 'ER Iso wall shoulder external rotation', NULL, NULL),
  ('056-ABD-ISOMETRIC-WALL-SHOULDER-', 'ABD Isometric wall shoulder abducion', NULL, NULL),
  ('057-BELLY-PRESS-IR', 'Belly press IR', 'En la posición de la imagen empuja la mano contra la zona abdominal IR Band isometric internal rotation Flexionar codo a 90º Colocar una toalla o similar entre codo y tronco Mantener la posición sin que te venza la goma', NULL),
  ('058-ESCAPULA', 'Escápula', 'Prone scapular A retraction Sin utilizar los brazos concéntrate en realizar a la vez los dos movimientos de la izquierda (abajo y centro) con las escápulas', NULL),
  ('059-RESISTED-A-SCAPULAR-RETRACTI', 'Resisted A scapular retraction', 'Sin utilizar los brazos concéntrate en realizar a la vez los dos movimientos de la izquierda (abajo y centro) con las escápulas', NULL),
  ('060-SERRATO-SERRATUS-PUNCH-BAND', 'Serrato Serratus punch band', 'Evita arquear la espalda o adelantar cabeza, a-core', NULL),
  ('061-ISOMETRIC-WALL-SQUAT', 'Isometric wall squat', 'Piernas a la anchura de las caderas Flexionado a 90º empujar contra la pared Isometric 1 leg wall squat', NULL),
  ('062-1-LEG-ISOMETRIC-CALF-90', '1 leg isometric calf 90º', 'Asegurarse que el talón no sobrepasa la línea del apoyo generando un ángulo más cerrado para el tobillo', NULL),
  ('063-FRONTAL-SIDE-WALL-ISO-PUSH', 'frontal Side wall iso push', 'No extender del todo la pierna de apoyo La fuerza viene del empuje contra el suelo', NULL),
  ('064-CLPC', 'CLPC', 'Hip mobility 360º', NULL),
  ('065-CLOSED-CHAIN-HIP-LOCK', 'Closed chain hip lock', 'Activa core durante todo el movimiento; trata de mantener alineada la espalda', NULL),
  ('066-TALL-KNEELING-LMN-HIP-EXTENS', 'Tall kneeling LMN hip extension', 'Muñecas rígidas y y a-core Activa gluteos', NULL),
  ('067-RAQUIS', 'Raquis', 'Draw in supino Acostado boca arriba con las rodillas flexionadas Piensa en llevar el ombligo al suelo todo lo que puedas y aguanta la posición', NULL),
  ('068-KB-BOTTOM-UP', 'KB bottom up', 'Mantener brazo a 90º con un peso que te permita que la KB no caiga hacia los lados No pierdas la curvatura lumbar No adelantar cabeza, mantener la muñeca firme y A-core', NULL),
  ('069-HALF-KNEELING-KB-BOTTOM-UP', 'Half kneeling KB bottom up', 'KB no caiga hacia los lados No pierdas la curvatura lumbar No adelantar cabeza, mantener la muñeca firme y A-core', NULL),
  ('070-KB-BOTTOM-UP-PRESS', 'KB bottom up press', 'KB no caiga hacia los lados No pierdas la curvatura lumbar No adelantar cabeza, mantener la muñeca firme y A-core', NULL),
  ('071-ALTERNATIVE-KB-BOTTOM-UP-PRE', 'Alternative KB bottom up press', 'KB no caiga hacia los lados No pierdas la curvatura lumbar No adelantar cabeza, mantener la muñeca firme y A-core', NULL),
  ('072-AIR-HALF-KNEELING-A-RETRACTI', 'Air half kneeling A retraction', NULL, NULL),
  ('073-ASOCIATIVOS', 'ASOCIATIVOS', 'Miembro Pierna Fase 1: CCC con carga/descarga Sagital Resisted knee extensión Dejarse vencer por la fuerza y de la goma y después vencerla extendiendo rodilla', NULL),
  ('074-POSTERIOR', 'posterior', 'Posterior ball Calf raises Sujeta la pelota presionando con los tobillos y realiza mientras elevaciones de talón', NULL),
  ('075-FRONTAL-FIRE-HYDRANT-ISO-HOL', 'Frontal Fire Hydrant ISO hold', 'Eleva la pierna lo justo para no perder la posición simétrica de la cadera Mantén la espalda alineada y A-Core ADD Puente glúteo excentrico + isométrico de aductores Utiliza una pelota, un bloque o algo similar para apretar juntando” piernas Activa glúteos y core durante todo el movimiento Controla la bajada', NULL),
  ('076-0-20', '0:20', 'ABD Isometric hip abduction Genera estabilidad desde el apoyo en el suelo y a-core Empujar la pelota tratando de llevar la pierna hacia la pared', NULL),
  ('077-BRIDGE-PSOAS-MARCH', 'Bridge psoas march', NULL, NULL),
  ('078-PELVIC-TILT', 'Pelvic tilt', 'Knee ext 90/90 knee rolls Aprieta el roller pelota o lo que utilices; Eleva el glúteo del suelo; Deliza sobre el roller alternando la elevación de rodillas', NULL),
  ('079-FASE-2-ESTABILIZACION-TRANSI', 'Fase 2: Estabilización transicional', 'Bisagra de cadera con pica Mantener espalda alineada Activa glúteos y core en todo el movimiento Ve desplazando el glúteo hacia atrás manteniéndolo activo y cuando no avance más detén la bajada', NULL),
  ('080-LUNGE-FOOT-OVER-PLATE', 'Lunge foot over plate', 'Mantener el tobillo a 90º, no como en el video', NULL),
  ('081-FASE-3-ESTABILIZACION-DINAMI', 'Fase 3: estabilización dinámica', 'Fase 1: CCC con carga/descarga All four abs Desde posición de cuadrupedia curva la espalda tanto como puedas hacia arriba; inclínate hacia delante y desde ahí toma aire agrandando el espacio entre escápulas; después sopla fuerte llevando el ombligo hacia dentro.', NULL),
  ('082-BISAGRA-DE-CADERA-CON-RODILL', 'Bisagra de cadera con rodilla sobre banco', 'Mantener espalda alineada Activa glúteos y core en todo el movimiento Ve desplazando el glúteo hacia atrás manteniéndolo activo, cuando no avance más detén la bajada 2x15 Lado', NULL),
  ('083-ANTI-EXT-BIRD-DOG', 'Anti Ext Bird dog', 'Mantener espalda alineada Activa el glúteo de pierna elevada y A-core Hazlo lento y controlado 2x12', NULL),
  ('084-1-40', '1:40', 'Kneeling elasctic high anti extension Mantener espalda alineada; No adelantar cabeza Activa el glúteos y A-core ; Hazlo lento y controlado', NULL),
  ('085-ROLL-OUT', 'Roll out', 'Mantener espalda alineada Que no “caiga el culo Lento y controlado Body saws Comienza desde una posición de plancha frontal Mueve el cuerpo hacia delante y atrás sobre las puntas de tus pies. A-core durante todo el ejercicio', NULL),
  ('086-HOLLOW-HOLD', 'Hollow hold', 'A-Core, flexionar cadera', NULL),
  ('087-HOLLOW-ROCKS', 'Hollow rocks', 'A-Core, flexionar cadera y balancearse', NULL),
  ('088-ISOMETRIC-DEADBUG-PUSH', 'Isometric deadbug push', 'No pierdas la curvatura lumbar Empuja fuerte las piernas contra los brazos A-core', NULL),
  ('089-CROSS-DEADBUG-PUSH', 'Cross deadbug push', 'No pierdas la curvatura lumbar Empuja fuerte las pierna contra el brazo contrario A-core', NULL),
  ('090-PELVIC-TILT-BANDED-DEADBUG', 'Pelvic tilt Banded deadbug', 'No pierdas la curvatura lumbar A-core', NULL),
  ('091-WAITER-WALK-SINGLE-ARM-CARRY', 'Waiter walk single arm carry', 'No pierdas la alineación del raquis Mantén todo el cuerpo, incluida cabeza en línea A-core', NULL),
  ('092-ANTI', 'Anti', 'Flex 1 leg glute bridge w tennis ball Coloca una pelota de tenis en tu cadera y sujétala flexionándola; realiza un puede glúteo a una pierna', NULL),
  ('093-KNEELING-SIDE-PLANK', 'Kneeling Side Plank', 'No pierdas la alineación del raquis Mantén todo el cuerpo, incluida cabeza en línea A-core Side Plank No pierdas la alineación del raquis Mantén todo el cuerpo, incluida cabeza en línea A-core Star plank No pierdas la alineación del raquis; a-core Mantén todo el cuerpo, incluida cabeza en línea Half kneeling raised anti inclination No pierdas la alineación del raquis; a-core Mantén todo el cuerpo, incluida cabeza en línea', NULL),
  ('094-DA-VINCI-PLANK', 'Da vinci plank', 'No pierdas la alineación del raquis Mantén todo el cuerpo, incluida cabeza en línea A-core', NULL),
  ('095-SEG-6', '(seg 6)', 'Dynamic Pallof Press Piernas a altura de caderas; a-core; empuja brazos hacia delante y mantén 2 segundos antes de volver', NULL),
  ('096-TALL-KNEELING-ANTI-ROT', 'Tall kneeling anti rot', 'Mantén la espalda alineada, evita que el tronco rote No adelantar cabeza A-core', NULL),
  ('097-INCLINACION', 'Inclinación', '+ rotatión Plank KB Pull Through Mantén la espalda alineada A-core', NULL),
  ('098-QUADRUPED-SHOULDER-EXT', 'Quadruped shoulder ext', 'Activar core', NULL),
  ('099-QUAD-SHOULDER-FLEX-CONTRALAT', 'Quad shoulder flex + contralateral hip ext', 'Mantener espalda alineada Evita que se rote el cuerpo', NULL),
  ('100-PUSH-UP-PLUS', 'Push up plus', 'Mantener espalda alineada Sin flexionar los codos acercarse y alejarse del suelo con los brazos', NULL),
  ('101-FRONTAL', 'Frontal', 'ER Side Lying Press Trata de elevar la pesa lo más “recta” posible', NULL),
  ('102-SIDE-PLANK-PRESS', 'Side plank press', 'Mantener espalda alineada Trata de elevar la pesa lo más “recta” posible', NULL),
  ('103-IR-SIDE-LYING-SHOULDER-EXTER', 'IR Side Lying Shoulder external rotation', 'Lleva la pesa hacia tu pecho', NULL),
  ('104-HALF-KNEELING-KETTLEBELL-WIN', 'Half kneeling kettlebell windmill', 'Activa core; realiza el movimientolento y controlado', NULL),
  ('105-CADENA', 'Cadena', 'Apoyo Fase 1: CCC con carga/descarga ISO cross step wall drill', NULL),
  ('106-SPLIT-STANCE-ROTATIONAL-LAND', 'Split-Stance Rotational Landmine Press', NULL, NULL),
  ('107-2-LEGS-POGOS', '2 legs pogos', 'Suelo quema” debes tocar el suelo poco tiempo No llegues a tocar con el talón el suelo IMPORTANTE: en aire debes llevar las puntas hacia arriba', NULL),
  ('108-ANKLE-EXTENSIVE-LINEAR-POGOS', 'Ankle extensive linear pogos', 'Suelo quema” debes tocar el suelo poco tiempo No llegues a tocar con el talón el suelo IMPORTANTE: en aire debes llevar las puntas hacia arriba', NULL),
  ('109-FORWARD-BACKWARDS-POGO-JUMPS', 'Forward Backwards Pogo Jumps (delante detrás)', 'Suelo quema” debes tocar el suelo poco tiempo No llegues a tocar con el talón el suelo IMPORTANTE: en aire debes llevar las puntas hacia arriba', NULL),
  ('110-FRONTAL-2-LEGS-SIDE-POGOS-DE', 'Frontal 2 legs side pogos ( de lado a lado)', 'Suelo quema” debes tocar el suelo poco tiempo No llegues a tocar con el talón el suelo IMPORTANTE: en aire debes llevar puntas hacia arriba', NULL),
  ('111-ANKLE-AISMETRIC-EXTENSIVE-PO', 'Ankle aismetric extensive pogos', 'Suelo quema” debes tocar el suelo poco tiempo No llegues a tocar con el talón el suelo IMPORTANTE: en aire debes llevar las puntas hacia arriba', NULL),
  ('112-KNEE-EXTENSIVE-PLYOS-1-LEG-B', 'Knee extensive plyos 1 leg box', 'Haz saltos pequeños manteniendo alineados tobillo rodilla y cadera', NULL),
  ('113-FARMER-WALK', 'Farmer walk', 'Trata de mantener activo core Hazlo relativamente lento Manipulaciones Fase 1: CCC con carga/descarga Fase 2: Estabilización transicional Turkish Get Up - Step 1-2', NULL),
  ('114-TURKISH-GET-UP-STEP-3', 'Turkish Get Up - Step 3', NULL, NULL),
  ('115-TURKISH-GET-UP-STEP-4', 'Turkish Get Up - Step 4', 'Manteniendo elevada la KB nos levantamos a-core', NULL),
  ('116-1-ARM-ROTATIONAL-TWX-ROW', '1 arm rotational TWX row', 'Realizar el movimiento lento a-core Durante la tracción realizar retracción escapular', NULL),
  ('117-LMN-KNEELING-LATERAL-PRESS', 'LMN Kneeling Lateral Press', 'Tratar de mantener alineado el brazo con el tronco durante todo el movimiento A-core', NULL),
  ('118-1-LEG-RDL-ROTATION-4-POSITIO', '1 leg RDL rotation + 4 position', 'Mantén la posición de la espalda alineada Pie-rodilla-cadera alineadas', NULL),
  ('119-1-LEG-KB-HALO', '1 leg KB halo', 'Mantén la posición de la espalda alineada Pie-rodilla-cadera alineadas Rodilla elevada a la altura de la cadera sin arquear zona lumbar', NULL),
  ('120-KB-SINGLE-LEG-CALF-RAISE-ISO', 'KB Single Leg Calf Raise Isometric Hold 90º', 'Mantener el tobillo a 90º; con un brazo te sujetas a pared o Rack para estabilizar; sujeta una KB con el otro y mantén la posición - Movimiento libre o Mecánica Skippng Flow Seguir instrucciones', NULL),
  ('121-HIP', 'Hip', 'Ankle Wall hip lock Desde arriba con tobillo y caderas extendidas bajas llevando la cadera hacia atrás y llevando el tobillo al suelo dejando el espacio de una tarjeta de crédito del talón al suelo', NULL),
  ('122-O-CONTEXTO', 'o Contexto', 'o Realidad PRINCIPALES Empuje horizontal One arm press elastic resitance Mantén el tronco alineado A-core Push up elastic resistance Mantén el tronco alineado; forma una “A” con los brazos; A-core Empuje horizontal Asegúrate de llegar a todo el rango con ambos brazos Mantén las muñecas “vivas”(que no se extiendan) DB Bench press Generar separación de codos respecto al tronco de 45º Muñecas rígidas y por encima de los codos y a-core Los brazos no se acercan demasiado al cuerpo', NULL),
  ('123-INCLINED-DB-BENCH-PRESS', 'Inclined DB Bench press', 'Generar separación de codos respecto al tronco de 45º Muñecas rígidas y por encima de los codos y a-core Los brazos no se acercan demasiado al cuerpo', NULL),
  ('124-BENCH-PRESS', 'Bench press', 'Pierde poca velocidad en concéntrico a lo largo de las repeticiones Muñecas rígidas y directamente por encima de los codos y a-core Los brazos no se acercan demasiado al cuerpo', NULL),
  ('125-SEATED-1-ARM-CABLE-PRESS', 'Seated 1 arm cable press', 'Muñeca rígida, no se extiende Codo cercano al cuerpo No adelantar cabeza manteniendo espalda alineada', NULL),
  ('126-1-ARM-CABLE-PRESS-SPLIT-STAN', '1 arm cable press Split stance', 'Muñeca rígida, no se extiende Codo cercano al cuerpo No adelantar cabeza manteniendo espalda alineada', NULL),
  ('127-HALF-KNEELING-LMN-PRESS', 'Half kneeling LMN press', 'No adelantar cabeza manteniendo espalda alineada', NULL),
  ('128-SPLIT-LMN-PRESS', 'Split LMN press', 'Mover solo el brazo, manteniendo estable el resto del cuerpo', NULL),
  ('129-TRACCION-HORIZONTAL', 'Tracción horizontal', 'Bent over row elastic resistance Mantén el tronco alineado; A-core Realiza retracción escapular durante la ejecución Stand row elastic resistance Mantén el tronco alineado; A-core Realiza retracción escapular durante la ejecución TRX row Mantén el tronco alineado; A-core Realiza retracción escapular durante la ejecución 1arm plank row elastic resistance Mantén el tronco alineado; A-core Realiza retracción escapular durante la ejecución Con mano apoyada sujeta la zona de la goma que necesites para alcanzar la intensidad necesaria Split stance cable row El tronco no se deja llevar hacia delante ni hacia atrás con el movimiento (controlar la carga para evitar) Al tirar realiza retracción escapular, A-core y mantén alineada la espalda', NULL),
  ('130-SINGLE-ARM-SINGLE-LEG-CABLE-', 'Single Arm Single Leg Cable Row', 'El tronco no se deja llevar hacia delante ni hacia atrás con el movimiento (controlar la carga para evitar)', NULL),
  ('131-TRACCION-HORIZONTAL-ASCENDEN', 'Tracción horizontal ascendente', 'Haz la retracción escapular antes de tirar Al tirar el codo puede quedar a la altura del tronco A-core', NULL),
  ('132-REMO-INVERTIDO-SUPINO', 'Remo invertido supino', 'Haz la retracción escapular antes de tirar a-core', NULL),
  ('133-SEATED-ROW', 'Seated row', 'Mantén la espalda alineada, a-core, no adelantar cabeza Al tirar acompaña el movimiento de una retracción escapular', NULL),
  ('134-1-ARM-BD-ROW', '1 arm BD row', 'Mantén la espalda alineada, a-core, no adelantar cabeza Al tirar acompaña el movimiento de una retracción escapular', NULL),
  ('135-DUAL-DB-PRONE-ROW', 'Dual DB prone row', 'No llevar los codos más arriba de la espalda', NULL),
  ('136-INCLINED-DB-ROW', 'Inclined DB row', 'Mantén la espalda alineada, a-core, no adelantar cabeza Al tirar acompaña el movimiento de una retracción escapular', NULL),
  ('137-DB-BENT-OVER-ROW', 'DB bent over row', 'Mantén la espalda alineada, a-core, no adelantar cabeza Al tirar acompaña el movimiento de una retracción escapular', NULL),
  ('138-BANDED-BENT-OVER-ROW', 'Banded Bent over row', 'Mantén la espalda alineada, a-core, no adelantar cabeza Al tirar acompaña el movimiento de una retracción escapular. Activa glúteos', NULL),
  ('139-EMPUJE-VERTICAL', 'Empuje vertical', 'Kneeling shoulder press Mantén el tronco alineado; A-core Seated shoulder press Mantén el tronco alineado; A-core Vertical push Asegúrate de llegar a todo el rango con ambos brazos Mantén las muñecas “vivas”(que no se extiendan) Neutral grip DB shoulder press No pierdas la curvatura lumbar, contrae los abdominales para evitarlo No adelantar cabeza A-core', NULL),
  ('140-1-ARM-90-SHOULDER-PRESS', '1 arm 90º shoulder press', 'Posicionar el hombro y codo a 90º, no bajar de ahí Mantener espalda alineada No adelantar cabeza', NULL),
  ('141-STANDING-NEUTRAL-GRIP-SHOULD', 'Standing neutral grip shoulder press', 'No pierdas la curvatura lumbar, contrae los abdominales para evitarlo No adelantar cabeza A-core', NULL),
  ('142-SHOULDER-PRESS-BB', 'Shoulder press BB', 'Mantener espalda alineada (att. Cuando BB esta arriba) No adelantar cabeza Muñecas activas, no “caen hacia atrás” y A-Core', NULL),
  ('143-TRACCION-VERTICAL', 'Tracción vertical', 'Half Kneeling Inlined 1arm row elastic resistance Mantén el tronco alineado; A-core Realiza retracción escapular durante la ejecución Half Kneeling Inlined row elastic resistance Mantén el tronco alineado; A-core Realiza retracción escapular durante la ejecución Seated vertical row elastic resistance Mantén el tronco alineado; A-core Realiza retracción escapular durante la ejecución Neutral grip vertical pull Inclínate un poco hacia atrás para realizar el ejercicio; no en cada repetición si no de manera continua Vertical pull Mantén el tronco alineado; A-core Realiza retracción escapular durante la ejecución Kneeling inclined single arm cable row Pierde poca velocidad en concéntrico a lo largo de las repeticiones Al tirar realiza retracción escapular, A-core y mantén alineada la espalda', NULL),
  ('144-BAND-ASISTED-PULL-UP', 'Band asisted pull up', 'Pierde poca velocidad en concéntrico a lo largo de las repeticiones Si no hay máquina utilizar elástico como en el video Retracción escapular previa', NULL),
  ('145-ECCENTRIC-ACENTUATED-CHIN-UP', 'Eccentric acentuated Chin Ups', 'Elévate sobre una superficie para comenzar desde arriba en la barra y bajar poco a poco', NULL),
  ('146-DOMINANTES-RODILLA', 'Dominantes rodilla', 'Elastic Front squat elastic resistance Sujeta con los dedos al lado de los hombros, codos arriba Bajar hasta el punto previo a perder la curvatura lumbar A-core Front split squat elastic resistance Sujeta con los dedos al lado de los hombros, codos arriba Bajar hasta el punto previo a perder la curvatura lumbar A-core Triangle squat elastic resistance No hace falta subir la goma tanto como en la imagen Pese a la rotación tratar de mantener alineado tronco A-core Isometric press machine Posicionar rodillas a 90º y ejercer fuerza contra una carga que no puedas desplazar En este caso debes ejercer un empuje a una intensidad % Isometric hack machine Posicionar rodillas a XXº y ejercer fuerza contra una carga que no puedas desplazar En este caso debes ejercer un empuje a una intensidad %', NULL),
  ('147-ECCENTRIC-PRESS-MACHINE', 'Eccentric press machine', 'Concéntrate en tardar los … segundos de la dosis la bajar', NULL),
  ('148-1-LEG-ACENTUATED-ECC-PRESS-M', '1 leg acentuated ecc press machine', 'Mueve la carga con dos piernas y resiste en excéntrico con una sola pierna', NULL),
  ('149-2-LEGS-PRESS-MACHINE', '2 legs press machine', 'Isometric Rack Back Squat Pies simétricos, espalda alineada, A-Core Asegúrate de no perder curva lumbar', NULL),
  ('150-ISOMETRIC-SPANISH-SQUAT', 'Isometric spanish squat', 'Colocar la goma en la parte posterior de las piernas Tomar la posición de la imagen (no hace falta adelantar brazos) Evita inclinar el tronco', NULL),
  ('151-ISO-WEIGHTED-SPANISH-SQUAT', 'Iso weighted Spanish squat', 'Colocar la goma en la parte posterior de las piernas Tomar la posición de la imagen, evita inclinar el tronco USA UNA KB SOBRE CADERA PARA LOGRAR EL %', NULL),
  ('152-WEIGHTED-SPANISH-SQUAT', 'Weighted Spanish squat', 'Colocar la goma en la parte posterior de las piernas', NULL),
  ('153-1-LEG-TRX-SQUAT', '1 leg TRX squat', 'Trata de mantenerte erguido durante todo el ejercicio Procure que las rodillas no se acerquen la una a la otra', NULL),
  ('154-KB-2-HANDS-CLEAN', 'KB 2 hands clean', 'Ve desplazando los glúteos hacia atrás manteniéndolos activos, cuando no avance más detén la bajada Ver como cambia el agarre durante la ejecución en el video, la KB cerca del cuerpo Activa glúteos y core', NULL),
  ('155-MIN-1-00', 'min 1:00', 'Single-leg squat Trata de mantenerte erguido durante todo el ejercicio; Procure que las rodillas no se acerquen la una a la otra; No hace falta que estiras la pierna adelantada, puedes flexionar la cadera elevando la rodilla', NULL),
  ('156-SPLIT-BACK-SQUAT', 'Split back squat', 'Mantener en todo momento curvatura lumbar; a-core La mayor parte de la fuerza se realiza con la pierna adelantada', NULL),
  ('157-BACK-SQUAT', 'Back squat', 'Bajar hasta el punto previo a perder la curvatura lumbar A-core', NULL),
  ('158-GOBLET-SQUAT', 'Goblet squat', 'Bajar hasta el punto previo a perder la curvatura lumbar A-core y espalda alineada, vigila zona torácica', NULL),
  ('159-SLIP-FRONT-SQUAT', 'Slip Front squat', 'Sujeta con los dedos al lado de los hombros, codos arriba Bajar hasta el punto previo a perder la curvatura lumbar A-core. La fuerza la realizas con la pierna adelantada', NULL),
  ('160-FRONT-SQUAT', 'Front squat', 'Sujeta con los dedos al lado de los hombros, codos arriba Bajar hasta el punto previo a perder la curvatura lumbar A-core', NULL),
  ('161-HACK-MACHINE-SQUAT', 'Hack machine squat', 'Posicionar rodillas a la altura de las caderas', NULL),
  ('162-FRONTAL-ISOMETRIC-LATERAL-SQ', 'Frontal Isometric lateral squat + 2 KB', 'Punta del pie alejado apunta hacia delante Mantener alineación del tronco a-core Lado', NULL),
  ('163-GOBLET-TRIANGLE-SQUAT', 'Goblet triangle squat', 'Punta del pie alejado apunta hacia delante Mantener alineación del tronco a-core Lado', NULL),
  ('164-DB-TRIANGLE-SQUAT', 'DB triangle squat', 'Punta del pie alejado apunta hacia delante Mantener alineación del tronco a-core', NULL),
  ('165-LMN-LATERAL-REVERSE-LUNGE', 'LMN Lateral Reverse Lunge', 'La pierna adelantada es la que produce la fuerza empujando el suelo; Mantener correcta alineación del tronco sin llevar la cadera hacia los lados Lado', NULL),
  ('166-LMN-LATERAL-SQUAT', 'LMN Lateral Squat', 'La pierna adelantada es la que produce la fuerza empujando el suelo; Mantener correcta alineación del tronco Lado', NULL),
  ('167-LMN-TRIANGLE-SQUAT', 'LMN triangle Squat', 'Los pies siempre apuntando hacia delante; Mantener correcta alineación del tronco', NULL),
  ('168-LMN-TRIANGLE-LUNGE-LOW-GRIP', 'LMN triangle Lunge Low grip', 'Los pies siempre apuntando hacia delante; Mantener correcta alineación del tronco; Empuja el suelo fuerte para volver a posición inicial Lado', NULL),
  ('169-COSSACK-SQUAT', 'Cossack squat', 'Utiliza un rack para cargar la barra no como en el video', NULL),
  ('170-LMN-TRIANGLE-LUNGE-TO-PUSH-P', 'LMN Triangle Lunge to Push Press Lado', NULL, NULL),
  ('171-DOMINANTES-CADERA', 'Dominantes cadera', 'Romanian elastic resistance Durante el movimiento los glúteos se desplazan hacia delante y atrás con rodillas algo flexionadas, A-core Mantén la espalda alineada en todo el movimiento Deadlift elastic resistance Durante el movimiento los glúteos se desplazan hacia delante y atrás con rodillas algo flexionadas, A-core Mantén la espalda alineada en todo el movimiento KB romanian Durante el movimiento los glúteos se desplazan hacia delante y atrás con rodillas algo flexionadas, A-core Mantén la espalda alineada en todo el movimiento', NULL),
  ('172-SINGLE-ARM-KB-DEADLIFT', 'Single arm KB deadlift', 'Durante el movimiento los glúteos se desplazan hacia delante y atrás con rodillas algo flexionadas, A-core,espalda alineada, evita rotar el tronco', NULL),
  ('173-SINGLE-LEG-ROMANIAN-VIDEO-DE', 'Single leg romanian (video de la derecha)', 'La pierna que se desplaza hacia atrás lo hace como una pata de palo”. La apoyada desplaza el glúteo hacia atrás y delante con la rodilla algo flexionada. A-core Mantén la espalda alineada en todo el movimiento', NULL),
  ('174-SPLIT-ROMANIAN-VIDEO-DE-LA-D', 'Split Romanian (video de la derecha)', 'En posición asimétrica el glúteo se desplaza hacia delante y atrás con rodilla algo flexionada, A-core Mantén la espalda alineada en todo el movimiento La fuerza la realizas con la pierna adelantada', NULL),
  ('175-ROMANIAN-BAJAR-HASTA-EL-FINA', 'Romanian (Bajar hasta el final de la rodilla)(En el video es el 2do ej)', 'Durante el movimiento los glúteos se desplazan hacia delante y atrás con rodillas algo flexionadas, A-core Mantén la espalda alineada en todo el movimiento', NULL),
  ('176-BANDED-DEALIFT', 'Banded dealift', 'Durante el movimiento los glúteos se desplazan hacia delante y atrás con rodillas algo flexionadas, A-core Mantén la espalda alineada en todo el movimiento', NULL),
  ('177-ISO-ISOMETRIC-KB-SUMO-SQUAT', 'ISO Isometric KB sumo squat', 'Separar piernas y bajar quedando la KB por debajo de las rodillas Mantener alineada la espalda', NULL),
  ('178-PIMA', 'PIMA', 'Natera 1leg hip ISO push', NULL),
  ('179-ISO-1LEG-FLOOR-HIP-ISO-PUSH', 'ISO 1leg floor hip iso push', 'Activar glúteo y core antes de iniciar el empuje Apoyar solo el talón del pie', NULL),
  ('180-ISO-1-LEG-BENCH-ISO-HIP-THRU', 'ISO 1 leg bench iso hip thrust', 'Gluteo y core active durante todo el ejercicio USA UNA KB SOBRE CADERA PARA LOGRAR EL % Apoyar solo el talón y no elevar cabeza', NULL),
  ('181-ISO-ISOMETRIC-WALL-SINGLE-LE', 'ISO Isometric Wall Single Leg RDL', 'Mantener espalda alineada y a-core Mantener glúteo de pierna apoyada activo', NULL),
  ('182-FLOOR-HIP-THRUST', 'Floor hip thrust', 'Activa glúteos antes de iniciar ejercicio mantenlos ac A-core', NULL),
  ('183-HIP-THRUST', 'Hip thrust', 'Mantener alineada la espalda durante todo el ejercicio A-Core y glúteos; “subir y bajar como una bisagra', NULL),
  ('184-1LEG-HIP-THRUST', '1leg Hip thrust', 'Mantener alineada la espalda durante todo el ejercicio A-Core y glúteos; “subir y bajar como una bisagra', NULL),
  ('185-HEXA-BAR-SQUAT', 'Hexa bar squat', 'Pies a la altura de las caderas Mantener alineada la espalda, cabeza incluida en todo momento, a-core', NULL),
  ('186-KANG-SQUAT', 'Kang squat', 'Pies a la altura de las caderas Mantener alineada la espalda, Llevar glúteos hacia atrás, abajo, atrás y arriba', NULL),
  ('187-LUNGES', 'Lunges', 'Lunge crossed elastic resistance Mantén la posición de la espalda alineada Al bajar para mantener la posición hacerlo como un ascensor, de manera que no nos inclinemos Lunge crossed elastic resistance Mantén la posición de la espalda alineada Al bajar para mantener la posición hacerlo como un ascensor, de manera que no nos inclinemos Isometric lunge Mantén la posición de la espalda alineada', NULL),
  ('188-ISOMETRIC-BULGARIAN', 'Isometric Bulgarian', 'Mantén la posición de la espalda alineada Al bajar para mantener la posición hacerlo como un ascensor, de manera que te nos inclinemos Bulgarian Smith machine Mantén la posición de la espalda alineada Al bajar para mantener la posición hacerlo como un ascensor, de manera que no te inclinemos', NULL),
  ('189-ISOMETRIC-STEP-UP', 'Isometric step up', 'SUJETA UN PESO QUE TE PERMITA ALCANZAR LA DOSIS', NULL),
  ('190-TIBA', 'Tiba', 'neutral Static lunge Evita que la rodilla adelantada de desplace hacia delante', NULL),
  ('191-DB-LUNGE', 'DB Lunge', 'Mantén la posición de la espalda alineada Pie-rodilla-cadera alineadas durante la zancada', NULL),
  ('192-TALL-KNEELING-TO-STANDING-KB', 'Tall kneeling to standing KB rack', 'Mantén la posición de la espalda alineada Pie-rodilla-cadera alineadas durante la zancada', NULL),
  ('193-REVERSE-LUNGE-KB-RACK', 'Reverse lunge KB rack', 'Mantén la posición de la espalda alineada Pie-rodilla-cadera alineadas', NULL),
  ('194-CURTSY-SQUAT', 'Curtsy squat', NULL, NULL),
  ('195-STEP', 'Step', 'ups Alternating step ups Mantén la posición de la espalda alineada Pie-rodilla-cadera alineadas', NULL),
  ('196-DB-STEP-UP', 'DB step up', 'Mantén la posición de la espalda alineada Pie-rodilla-cadera alineadas', NULL),
  ('197-SIDE-STEP-UP', 'Side step up', NULL, NULL),
  ('198-FRONTAL-LMN-LATERAL', 'Frontal LMN lateral', NULL, NULL),
  ('199-OLIMPICOS-DERIVADOS-E-ISO-RF', 'OLIMPICOS, derivados e iso(RFD)', 'Pime Natera knee iso push Parte MEDIA pie bajo barra con hombros caderas- tobillos alineados, barra sobre trapecios Rodilla flex 140-145º Caderas flex 160-165º Ángulo tronco entre 10-15º', NULL),
  ('200-NATERA-ANKLE-ISO-PUSH', 'Natera ankle iso push', 'Parte delantera pie bajo barra, rodilla extendida Ligera inclinación tronco hacia delante 5º Tobillo ligeramente dorsiflex 5º CDM hacia delante Ligera elevación del talón, 5º plantar flex', NULL),
  ('201-CLEAN-KB-2-HANDS-CLEAN', 'Clean KB 2 hands clean', 'Ve desplazando los glúteos hacia atrás manteniéndolos activos, cuando no avance más detén la bajada Ver como cambia el agarre durante la ejecución en el video, la KB cerca del cuerpo Activa glúteos y core', NULL),
  ('202-SNATCH-DB-SPLIT-LUNGE-SNATCH', 'Snatch DB split lunge snatch', NULL, NULL),
  ('203-DB-SNATCH', 'DB snatch', 'Supe la mancuerna cerca del cuerpo como si quisieras quitarte la camiseta A-core', NULL),
  ('204-PUSHPRES-DB-PUSH-OFF-PRESS', 'PushPres DB push off press', 'Aprovecha el impulso empujando con las piernas Cuando este DB arriba estas descansan sobre los hombros No adelantar cabeza, mantener espalda alineada', NULL),
  ('205-BB-JUMPS', 'BB jumps', 'Sujeta bien la barra contra los trapecios asegurando que no se “despegue” durante el salto para evitar que esta nos golpee', NULL),
  ('206-HEXABAR-HIGH-PULL', 'Hexabar high pull', 'Mantener alineada la espalda durante todo el ejercicio A-core', NULL),
  ('207-BOX-JUMP', 'Box jump', 'Salta hacia el cajón cayendo sobre este con las rodillas y caderas extendidas como en la muestra 2 del video, NO la uno', NULL),
  ('208-JUMP-FLEX-OVER-BOX', 'Jump flex over box', NULL, NULL),
  ('209-WEIGHTED-BOX-JUMP', 'Weighted box jump', 'Utiliza un peso que te permita saltar sobre un cajón de 20cm. Trata de llegar al cajón con las piernas extendidas', NULL),
  ('210-FRONT-CMJ-STOP', 'Front CMJ & stop', NULL, NULL),
  ('211-STEP-UP-JUMP', 'Step up jump', 'Salta lo más alto que puedas frontal Lateral box jump Salta hacia el cajón cayendo sobre este con las rodillas y caderas extendidas', NULL),
  ('212-SIDE-TO-SIDE-FLEX-BOX-JUMP', 'Side to side flex box jump', NULL, NULL),
  ('213-KB-LATERAL-DROP-CATCH-TO-LUN', 'KB Lateral Drop-Catch to Lunge', 'Mantén alineada la espalda a-core', NULL),
  ('214-TRANSVERS-SIDE-TO-SIDE-1LEG-', 'transvers Side to side 1leg box jump', 'Controla la alineación del tronco, NO utilizar un cajón demasiado alto', NULL),
  ('215-WALLBALL-PUNCH-THROW', 'Wallball punch throw', 'Concéntrate en transmitir la fuerza empujando contra el suelo Máxima velocidad', NULL),
  ('216-LMN-PUSH-PRESS', 'LMN push press', 'Empuja el suelo fuerte para llevar la barra arriba', NULL),
  ('217-STEP-BACK-1-ARM-CABLE-ROW', 'Step back 1 arm cable row', 'Manten la espalda alineada Empuja el suelo con la pierna adelantada', NULL),
  ('218-SHOCK-DROP-JUMP', 'Shock Drop jump', 'Trata de pasar el mínimo tiempo en el suelo', NULL),
  ('219-INFRA-ASSISTED-JUMPS', 'Infra Assisted jumps', 'Ayúdate de un elástico para saltar más Elevate rápido al tocar el suelo', NULL),
  ('220-SALTOS', 'Saltos', 'Mecanic Decelerations 2:2 Colócate de puntillas con los brazos arriba; después baja fuerte ayudándote de los brazos para bajar más rápido', NULL),
  ('221-DECELERATIONS-2-1', 'Decelerations 2:1', 'Colócate de puntillas con los brazos arriba; después baja fuerte ayudándote de los brazos para bajar más rápido', NULL),
  ('222-DROP-JUMP-DECELERATION', 'Drop jump deceleration', 'Déjate caer, no hace falta que extiendas la pierna tanto come el video, amortigua y quédate como una estatua', NULL),
  ('223-CMJ-DECELERATION', 'CMJ deceleration', 'Salta ayudándote de los brazos y al caer vas amortiguando la caída hasta quedar como una estatua', NULL),
  ('224-1-2-FRONT-JUMP', '1:2 front jump', 'Realiza un salto a una pierna; vigila estabilizar el cuerpo tras amortiguar la caída', NULL),
  ('225-1-1-FRONT-JUMP', '1:1 front jump', 'Realiza un salto a una pierna; vigila estabilizar el cuerpo tras amortiguar la caída', NULL),
  ('226-REVERSE-LUNGE-TO-JUMP', 'Reverse lunge to jump', NULL, NULL),
  ('227-1-1-SIDE-JUMP', '1:1 Side jump', 'Al aterrizar aguantar 3 segundos antes de volver a salta', NULL),
  ('228-1-1-90-JUMP', '1:1 90º jump', 'Al aterrizar aguantar 3 segundos antes de volver a salta', NULL),
  ('229-DROPS-SPLIT-REACTIVE-JUMP', 'Drops Split Reactive jump', NULL, NULL),
  ('230-SPLIT-BOX-DROP-JUMP', 'Split Box Drop jump', NULL, NULL),
  ('231-SINGLE-LEG-DROP-JUMP', 'Single leg drop jump', NULL, NULL),
  ('232-PLYO-EXTENSIVA', 'PLYO Extensiva', 'Off load cocontration Foam roller glute brige Apoya la parte media y delantera del pie sobre el roller; ponlo a una distancia que te permita alcanzar bien la dosis', NULL),
  ('233-ISOMETRIC-1LEG-FOAM-ROLLER-G', 'Isometric 1leg Foam roller glute brige', 'Apoya la parte media y delantera del pie sobre el roller; ponlo a una distancia que te permita alcanzar bien la dosis', NULL),
  ('234-FOAM-ROLLER-BRIGE-MARCH', 'Foam roller brige march', 'Apoya la parte media y delantera del pie sobre el roller; ponlo a una distancia que te permita alcanzar bien la dosis', NULL),
  ('235-AQUILLES', 'Aquilles', 'tolerance store & reléase energy Calf Pulses - Straight Knee Apoya la parte delantera del pie sobre el disco y comienza a hacer subidas y bajas con ritmo', NULL),
  ('236-LOW-LOAD', 'Low load', 'cocontration Penguin march Trata de llevar pa punta del pie lo más al techo posible mientras con la otra apoyas todo el pie a excepción del talón; golpeas el suelo para elevarte', NULL),
  ('237-0-32', '0:32', '90/90 single leg pogo Trata de llevar la punta del pie “hacia tu cabeza Golpea el suelo rápido “la pared quema', NULL),
  ('238-ASSISTED-1LEG-POGO', 'Assisted 1leg pogo', 'Sujétate a algo con el brazo, concéntrate en sacar la fuerza del tobillo, deja espacio de “tarjeta crédito Trata de llevar la punta del pie “hacia arriba Golpea el suelo rápido “el suelo quema', NULL),
  ('239-ASSISTED-1LEG-FRONT-BACK-POG', 'Assisted 1leg front & back pogo', 'Sujétate a algo con el brazo, concéntrate en sacar la fuerza del tobillo, deja espacio de “tarjeta crédito Trata de llevar la punta del pie “hacia arriba Golpea el suelo rápido “el suelo quema', NULL),
  ('240-SPLIT-STANCE-POGO-HOPS', 'Split stance pogo hops', 'Realizar los saltos a MENOR ALTURA QUE EL VIDEO Saltos cortos muy reactivos', NULL),
  ('241-LATERAL-DROP-JUMP-20CM', 'Lateral Drop Jump 20cm', 'Al caer se debe subir muy rápidamente “el suelo quema', NULL),
  ('242-STEP-BACK-UP-2-LEGS', 'Step back&up 2 legs', 'Al caer se debe subir muy rápidamente “el suelo quema', NULL),
  ('243-KNEE-STEP-UP-DOWN', 'knee Step up&down', 'Al caer se debe subir muy rápidamente “el suelo quema', NULL),
  ('244-STEP-SIDE-DOWN-UP-1LEG', 'Step side down&up 1leg', 'Al caer se debe subir muy rápidamente “el suelo quema', NULL),
  ('245-KNEE-PREP-OVER-STEP-KNEE', 'Knee Prep over step knee', 'Con rodilla flexionada tratar de “golpear” el suelo rápidamente “el suelo quema', NULL),
  ('246-PLYO-INTENSIVA', 'PLYO Intensiva', 'Box 40cm CMJ depth jump 2egs side CONTINUOUS Al caer puedes amortiguar un poco la caída, no es totalmente reactivo', NULL),
  ('247-MED-TUCK-JUMP', 'Med Tuck jump', 'Estar poco tiempo en el suelo Saltar lo + alto posible flexionando las caderas', NULL),
  ('248-MED', 'Med-', 'high Lateral skater hops', NULL),
  ('249-HIGH', 'High-', 'very H ?? Massai jumps No bloquear completamente la rodilla Concentrarse en saltar LO + ALTO POSIBLE con los tobillos', NULL),
  ('250-VERY', 'Very', 'high 1 leg hop jumps', NULL),
  ('251-MECANICAS', 'MECÁNICAS', 'Empuje lento de trineo A-core; empuja desde el suelo extendiendo pierna sin mover brazos', NULL),
  ('252-EMPUJE-PESADO-INTENCION-RAPI', 'Empuje pesado intención rápida', 'A-core; concéntrate en empujar suelo sin mover brazos', NULL);
